window.esdocSearchIndex = [
  [
    "",
    "test-file/tests/server/unit_tests/logic/email_logic_tests.js.html#lineNumber10",
    "#sendForgottenPasswordEmail",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/email_logic_tests.js.html#lineNumber17",
    "#sendForgottenPasswordEmail should send correct email",
    "test"
  ],
  [
    "overlord.hoist.io/server/areas/application/application_controller.js~applicationcontroller",
    "class/server/areas/application/application_controller.js~ApplicationController.html",
    "<span>ApplicationController</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/areas/application/application_controller.js</span>",
    "class"
  ],
  [
    "overlord.hoist.io/server/configuration/authentication.js~authenticationconfigurator",
    "class/server/configuration/authentication.js~AuthenticationConfigurator.html",
    "<span>AuthenticationConfigurator</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/configuration/authentication.js</span>",
    "class"
  ],
  [
    "overlord.hoist.io/server/configuration/base_configurator.js~baseconfigurator",
    "class/server/configuration/base_configurator.js~BaseConfigurator.html",
    "<span>BaseConfigurator</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/configuration/base_configurator.js</span>",
    "class"
  ],
  [
    "overlord.hoist.io/server/areas/base_controller.js~basecontroller",
    "class/server/areas/base_controller.js~BaseController.html",
    "<span>BaseController</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/areas/base_controller.js</span>",
    "class"
  ],
  [
    "overlord.hoist.io/server/areas/connector/connector_controller.js~connectorcontroller",
    "class/server/areas/connector/connector_controller.js~ConnectorController.html",
    "<span>ConnectorController</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/areas/connector/connector_controller.js</span>",
    "class"
  ],
  [
    "overlord.hoist.io/server/models/connector_view_model.js~connectorviewmodel",
    "class/server/models/connector_view_model.js~ConnectorViewModel.html",
    "<span>ConnectorViewModel</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/models/connector_view_model.js</span>",
    "class"
  ],
  [
    "overlord.hoist.io/server/areas/console/console_controller.js~consolecontroller",
    "class/server/areas/console/console_controller.js~ConsoleController.html",
    "<span>ConsoleController</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/areas/console/console_controller.js</span>",
    "class"
  ],
  [
    "overlord.hoist.io/server/areas/editor/editor_controller.js~editorcontroller",
    "class/server/areas/editor/editor_controller.js~EditorController.html",
    "<span>EditorController</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/areas/editor/editor_controller.js</span>",
    "class"
  ],
  [
    "overlord.hoist.io/server/areas/event/event_controller.js~eventcontroller",
    "class/server/areas/event/event_controller.js~EventController.html",
    "<span>EventController</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/areas/event/event_controller.js</span>",
    "class"
  ],
  [
    "overlord.hoist.io/server/areas/healthcheck/healthcheck_controller.js~healthcheckcontroller",
    "class/server/areas/healthcheck/healthcheck_controller.js~HealthcheckController.html",
    "<span>HealthcheckController</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/areas/healthcheck/healthcheck_controller.js</span>",
    "class"
  ],
  [
    "overlord.hoist.io/server/configuration/logging.js~loggingconfigurator",
    "class/server/configuration/logging.js~LoggingConfigurator.html",
    "<span>LoggingConfigurator</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/configuration/logging.js</span>",
    "class"
  ],
  [
    "overlord.hoist.io/server/areas/organisation/organisation_controller.js~organisationcontroller",
    "class/server/areas/organisation/organisation_controller.js~OrganisationController.html",
    "<span>OrganisationController</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/areas/organisation/organisation_controller.js</span>",
    "class"
  ],
  [
    "overlord.hoist.io/server/index.js~portalserver",
    "class/server/index.js~PortalServer.html",
    "<span>PortalServer</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/index.js</span>",
    "class"
  ],
  [
    "overlord.hoist.io/server/configuration/routes.js~routeconfigurator",
    "class/server/configuration/routes.js~RouteConfigurator.html",
    "<span>RouteConfigurator</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/configuration/routes.js</span>",
    "class"
  ],
  [
    "overlord.hoist.io/server/configuration/server.js~serverconfigurator",
    "class/server/configuration/server.js~ServerConfigurator.html",
    "<span>ServerConfigurator</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/configuration/server.js</span>",
    "class"
  ],
  [
    "overlord.hoist.io/server/areas/session/session_controller.js~sessioncontroller",
    "class/server/areas/session/session_controller.js~SessionController.html",
    "<span>SessionController</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/areas/session/session_controller.js</span>",
    "class"
  ],
  [
    "overlord.hoist.io/server/areas/user/user_controller.js~usercontroller",
    "class/server/areas/user/user_controller.js~UserController.html",
    "<span>UserController</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/areas/user/user_controller.js</span>",
    "class"
  ],
  [
    "overlord.hoist.io/server/logic/user.js~activateforgottenpassword",
    "function/index.html#static-function-activateForgottenPassword",
    "<span>activateForgottenPassword</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/user.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/utils/rabbit.js~closeconnection",
    "function/index.html#static-function-closeConnection",
    "<span>closeConnection</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/utils/rabbit.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/application.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/application.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/organisation.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/organisation.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/user.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/user.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/event.js~createevent",
    "function/index.html#static-function-createEvent",
    "<span>createEvent</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/event.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/user.js~createforgottenpassword",
    "function/index.html#static-function-createForgottenPassword",
    "<span>createForgottenPassword</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/user.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/event.js~createmoduleforevent",
    "function/index.html#static-function-createModuleForEvent",
    "<span>createModuleForEvent</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/event.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/session.js~createsessionforuser",
    "function/index.html#static-function-createSessionForUser",
    "<span>createSessionForUser</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/session.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/session.js~ensurelogin",
    "function/index.html#static-function-ensureLogin",
    "<span>ensureLogin</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/session.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/settings.js~getallsettings",
    "function/index.html#static-function-getAllSettings",
    "<span>getAllSettings</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/settings.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/application.js~getapplicationpath",
    "function/index.html#static-function-getApplicationPath",
    "<span>getApplicationPath</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/application.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/connector.js~getauthurl",
    "function/index.html#static-function-getAuthUrl",
    "<span>getAuthUrl</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/connector.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/connector.js~getavailableconnectors",
    "function/index.html#static-function-getAvailableConnectors",
    "<span>getAvailableConnectors</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/connector.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/editor.js~getcodeforevent",
    "function/index.html#static-function-getCodeForEvent",
    "<span>getCodeForEvent</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/editor.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/connector.js~getconnectorsforapplication",
    "function/index.html#static-function-getConnectorsForApplication",
    "<span>getConnectorsForApplication</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/connector.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/event.js~getevents",
    "function/index.html#static-function-getEvents",
    "<span>getEvents</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/event.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/console.js~getmessages",
    "function/index.html#static-function-getMessages",
    "<span>getMessages</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/console.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/utils/rabbit.js~getmessages",
    "function/index.html#static-function-getMessages",
    "<span>getMessages</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/utils/rabbit.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/session.js~getsessiondetails",
    "function/index.html#static-function-getSessionDetails",
    "<span>getSessionDetails</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/session.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/connector.js~getuniqueconnectorkey",
    "function/index.html#static-function-getUniqueConnectorKey",
    "<span>getUniqueConnectorKey</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/connector.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/connector.js~loadconnector",
    "function/index.html#static-function-loadConnector",
    "<span>loadConnector</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/connector.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/session.js~loglogin",
    "function/index.html#static-function-logLogin",
    "<span>logLogin</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/session.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/event.js~mapeventtomodule",
    "function/index.html#static-function-mapEventToModule",
    "<span>mapEventToModule</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/event.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/connector.js~populateconnector",
    "function/index.html#static-function-populateConnector",
    "<span>populateConnector</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/connector.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/utils/string_utils.js~sanitisename",
    "function/index.html#static-function-sanitiseName",
    "<span>sanitiseName</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/utils/string_utils.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/editor.js~savescript",
    "function/index.html#static-function-saveScript",
    "<span>saveScript</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/editor.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/emails.js~sendforgottenpasswordemail",
    "function/index.html#static-function-sendForgottenPasswordEmail",
    "<span>sendForgottenPasswordEmail</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/emails.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/emails.js~sendnouseracountemail",
    "function/index.html#static-function-sendNoUserAcountEmail",
    "<span>sendNoUserAcountEmail</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/emails.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/connector.js~setupdefaultconnector",
    "function/index.html#static-function-setupDefaultConnector",
    "<span>setupDefaultConnector</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/connector.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/utils/rabbit.js~setupqueue",
    "function/index.html#static-function-setupQueue",
    "<span>setupQueue</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/utils/rabbit.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/session.js~updateapplication",
    "function/index.html#static-function-updateApplication",
    "<span>updateApplication</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/session.js</span>",
    "function"
  ],
  [
    "overlord.hoist.io/server/logic/session.js~updateorganisation",
    "function/index.html#static-function-updateOrganisation",
    "<span>updateOrganisation</span> <span class=\"search-result-import-path\">overlord.hoist.io/server/logic/session.js</span>",
    "function"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/application_tests.js.html#lineNumber7",
    "ApplicationLogic",
    "test"
  ],
  [
    "getapplicationpath server/logic/application.js~getapplicationpath,getapplicationpath",
    "test-file/tests/server/unit_tests/logic/application_tests.js.html#lineNumber9",
    "ApplicationLogic #getApplicationPath",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/application_tests.js.html#lineNumber24",
    "ApplicationLogic #getApplicationPath returns application real path",
    "test"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "connectorcontroller server/areas/connector/connector_controller.js~connectorcontroller,connectorcontroller",
    "test-file/tests/server/unit_tests/controllers/connector_controller_tests.js.html#lineNumber9",
    "ConnectorController",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/connector_controller_tests.js.html#lineNumber89",
    "ConnectorController #connect",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/connector_controller_tests.js.html#lineNumber139",
    "ConnectorController #connect should pass correct return url to bouncer",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/connector_controller_tests.js.html#lineNumber134",
    "ConnectorController #connect should request the correct bucket key to bouncer",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/connector_controller_tests.js.html#lineNumber127",
    "ConnectorController #connect should return redirect url",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/connector_controller_tests.js.html#lineNumber87",
    "ConnectorController #getAvailable",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/connector_controller_tests.js.html#lineNumber88",
    "ConnectorController #getTriggers",
    "test"
  ],
  [
    "connectorcontroller#list server/areas/connector/connector_controller.js~connectorcontroller#list,connectorcontroller#list",
    "test-file/tests/server/unit_tests/controllers/connector_controller_tests.js.html#lineNumber15",
    "ConnectorController #list",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/connector_controller_tests.js.html#lineNumber74",
    "ConnectorController #list loads up connectors based on current application",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/connector_controller_tests.js.html#lineNumber39",
    "ConnectorController #list returns list of orgs current connectors",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/connector_logic_tests.js.html#lineNumber6",
    "ConnectorLogic",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/connector_logic_tests.js.html#lineNumber7",
    "ConnectorLogic #setupDefaultConnector",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/connector_logic_tests.js.html#lineNumber82",
    "ConnectorLogic #setupDefaultConnector if default connector key already exists",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/connector_logic_tests.js.html#lineNumber116",
    "ConnectorLogic #setupDefaultConnector if default connector key already exists should append a random number to key",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/connector_logic_tests.js.html#lineNumber9",
    "ConnectorLogic #setupDefaultConnector if no connector exists",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/connector_logic_tests.js.html#lineNumber71",
    "ConnectorLogic #setupDefaultConnector if no connector exists should look up root connector",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/connector_logic_tests.js.html#lineNumber66",
    "ConnectorLogic #setupDefaultConnector if no connector exists should return saved connector",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/connector_logic_tests.js.html#lineNumber51",
    "ConnectorLogic #setupDefaultConnector if no connector exists should save a new connector",
    "test"
  ],
  [
    "editorcontroller server/areas/editor/editor_controller.js~editorcontroller,editorcontroller",
    "test-file/tests/server/unit_tests/controllers/editor_controller_tests.js.html#lineNumber6",
    "EditorController",
    "test"
  ],
  [
    "connectorcontroller#list server/areas/connector/connector_controller.js~connectorcontroller#list,connectorcontroller#list",
    "test-file/tests/server/unit_tests/controllers/editor_controller_tests.js.html#lineNumber12",
    "EditorController #state",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/editor_controller_tests.js.html#lineNumber68",
    "EditorController #state returns list of current connectors and code",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/editor_tests.js.html#lineNumber8",
    "EditorLogic",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/editor_tests.js.html#lineNumber9",
    "EditorLogic #getCodeForEvent",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/editor_tests.js.html#lineNumber44",
    "EditorLogic #getCodeForEvent should return code",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/event_tests.js.html#lineNumber5",
    "EventLogic",
    "test"
  ],
  [
    "mapeventtomodule server/logic/event.js~mapeventtomodule,mapeventtomodule",
    "test-file/tests/server/unit_tests/logic/event_tests.js.html#lineNumber7",
    "EventLogic mapEventToModule",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/event_tests.js.html#lineNumber16",
    "EventLogic mapEventToModule returns correct module listing",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/organisation_tests.js.html#lineNumber1",
    "OrganisationLogic",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/organisation_tests.js.html#lineNumber3",
    "OrganisationLogic #create",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/organisation_tests.js.html#lineNumber2",
    "OrganisationLogic GetOrganisationBySlug",
    "test"
  ],
  [
    "portalserver server/index.js~portalserver,portalserver",
    "test-file/tests/server/unit_tests/server_tests.js.html#lineNumber9",
    "PortalServer",
    "test"
  ],
  [
    "portalserver#start server/index.js~portalserver#start,portalserver#start",
    "test-file/tests/server/unit_tests/server_tests.js.html#lineNumber15",
    "PortalServer #start",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/server_tests.js.html#lineNumber86",
    "PortalServer #start configures the hapi server with authentication",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/server_tests.js.html#lineNumber65",
    "PortalServer #start configures the hapi server with base configuration",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/server_tests.js.html#lineNumber72",
    "PortalServer #start configures the hapi server with logging",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/server_tests.js.html#lineNumber79",
    "PortalServer #start configures the hapi server with routes",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/server_tests.js.html#lineNumber62",
    "PortalServer #start connects to mongo",
    "test"
  ],
  [
    "sessioncontroller server/areas/session/session_controller.js~sessioncontroller,sessioncontroller",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html#lineNumber16",
    "SessionController",
    "test"
  ],
  [
    "sessioncontroller#create server/areas/session/session_controller.js~sessioncontroller#create,sessioncontroller#create",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html#lineNumber51",
    "SessionController #create",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html#lineNumber200",
    "SessionController #create if header contains x-real-ip",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html#lineNumber214",
    "SessionController #create if header contains x-real-ip uses override ip to validate user",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html#lineNumber205",
    "SessionController #create if header contains x-real-ip uses the override ip address to log login attempt",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html#lineNumber108",
    "SessionController #create if user validation fails",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html#lineNumber125",
    "SessionController #create if user validation fails logs an invalid login",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html#lineNumber115",
    "SessionController #create if user validation fails replies with error response",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html#lineNumber155",
    "SessionController #create if validation succeeds",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html#lineNumber173",
    "SessionController #create if validation succeeds logs a valid login",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html#lineNumber159",
    "SessionController #create if validation succeeds replies with session details",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html#lineNumber166",
    "SessionController #create if validation succeeds saves session to cookie",
    "test"
  ],
  [
    "sessioncontroller#destroy server/areas/session/session_controller.js~sessioncontroller#destroy,sessioncontroller#destroy",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html#lineNumber242",
    "SessionController #destroy",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html#lineNumber265",
    "SessionController #destroy clears current session",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html#lineNumber256",
    "SessionController #destroy returns simple message",
    "test"
  ],
  [
    "sessioncontroller#routes server/areas/session/session_controller.js~sessioncontroller#routes,sessioncontroller#routes",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html#lineNumber23",
    "SessionController #routes",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html#lineNumber28",
    "SessionController #routes defines a create route",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber13",
    "SessionLogic",
    "test"
  ],
  [
    "createsessionforuser server/logic/session.js~createsessionforuser,createsessionforuser",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber388",
    "SessionLogic #createSessionForUser",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber424",
    "SessionLogic #createSessionForUser with previous session",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber439",
    "SessionLogic #createSessionForUser with previous session with a selected organisation and application",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber458",
    "SessionLogic #createSessionForUser with previous session with a selected organisation and application creates session with matching application and organisation",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber444",
    "SessionLogic #createSessionForUser with previous session with a selected organisation and application loads the correct session",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber465",
    "SessionLogic #createSessionForUser with previous session with a selected organisation and application returns saved session",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber451",
    "SessionLogic #createSessionForUser with previous session with a selected organisation and application selects only the organisation and application fields",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber481",
    "SessionLogic #createSessionForUser with previous session without a selected organisation and application",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber502",
    "SessionLogic #createSessionForUser with previous session without a selected organisation and application creates session with last created organisation and last created application",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber509",
    "SessionLogic #createSessionForUser with previous session without a selected organisation and application finds last created application",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber518",
    "SessionLogic #createSessionForUser with previous session without a selected organisation and application returns saved session",
    "test"
  ],
  [
    "ensurelogin server/logic/session.js~ensurelogin,ensurelogin",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber15",
    "SessionLogic #ensureLogin",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber88",
    "SessionLogic #ensureLogin with invalid ip address",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber110",
    "SessionLogic #ensureLogin with invalid ip address doesn't load user",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber104",
    "SessionLogic #ensureLogin with invalid ip address returns rejection",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber150",
    "SessionLogic #ensureLogin with invalid password",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber158",
    "SessionLogic #ensureLogin with invalid password returns rejection",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber182",
    "SessionLogic #ensureLogin with invalid username",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber190",
    "SessionLogic #ensureLogin with invalid username returns rejection",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber114",
    "SessionLogic #ensureLogin with locked username",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber122",
    "SessionLogic #ensureLogin with locked username checks lock with user",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber135",
    "SessionLogic #ensureLogin with locked username doesn't check user password",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber129",
    "SessionLogic #ensureLogin with locked username returns rejection",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber48",
    "SessionLogic #ensureLogin with missing email",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber56",
    "SessionLogic #ensureLogin with missing email returns rejection",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber68",
    "SessionLogic #ensureLogin with missing password",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber76",
    "SessionLogic #ensureLogin with missing password returns rejection",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber214",
    "SessionLogic #ensureLogin with valid details",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber225",
    "SessionLogic #ensureLogin with valid details looks up user by lowercase email",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber219",
    "SessionLogic #ensureLogin with valid details returns user",
    "test"
  ],
  [
    "getsessiondetails server/logic/session.js~getsessiondetails,getsessiondetails",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber250",
    "SessionLogic #getSessionDetails",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber368",
    "SessionLogic #getSessionDetails looks up applications based on organisation",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber357",
    "SessionLogic #getSessionDetails looks up orgs based on user",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber347",
    "SessionLogic #getSessionDetails returns available applications",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber352",
    "SessionLogic #getSessionDetails returns available organisations",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber342",
    "SessionLogic #getSessionDetails returns current application",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber337",
    "SessionLogic #getSessionDetails returns current organisation",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber332",
    "SessionLogic #getSessionDetails returns current user",
    "test"
  ],
  [
    "loglogin server/logic/session.js~loglogin,loglogin",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber543",
    "SessionLogic #logLogin",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber558",
    "SessionLogic #logLogin with successful login",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber565",
    "SessionLogic #logLogin with successful login saves a success ip log",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber572",
    "SessionLogic #logLogin with successful login saves a success login log",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber590",
    "SessionLogic #logLogin with unsuccessful login",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber597",
    "SessionLogic #logLogin with unsuccessful login saves a fail ip log",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html#lineNumber604",
    "SessionLogic #logLogin with unsuccessful login saves a fail login log",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber6",
    "UserLogic",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber8",
    "UserLogic #create",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber82",
    "UserLogic #create if existing user with email",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber112",
    "UserLogic #create if existing user with email fails with invalid message",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber95",
    "UserLogic #create if existing user with email looks up correct user",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber39",
    "UserLogic #create if invalid email is supplied",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber44",
    "UserLogic #create if invalid email is supplied fails with invalid message",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber66",
    "UserLogic #create if missmatched supplied",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber75",
    "UserLogic #create if missmatched supplied fails with invalid message",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber27",
    "UserLogic #create if no email supplied",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber32",
    "UserLogic #create if no email supplied fails with invalid message",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber15",
    "UserLogic #create if no name supplied",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber20",
    "UserLogic #create if no name supplied fails with invalid message",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber51",
    "UserLogic #create if no password supplied",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber59",
    "UserLogic #create if no password supplied fails with invalid message",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber119",
    "UserLogic #create if valid credentials passed in",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber191",
    "UserLogic #create if valid credentials passed in creates application with correct name and organisation",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber184",
    "UserLogic #create if valid credentials passed in creates organisation with the users name",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber161",
    "UserLogic #create if valid credentials passed in returns a new user",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber168",
    "UserLogic #create if valid credentials passed in saves the user",
    "test"
  ],
  [
    "",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html#lineNumber177",
    "UserLogic #create if valid credentials passed in sets the user organisation",
    "test"
  ],
  [
    "server/areas/application/application_controller.js",
    "file/server/areas/application/application_controller.js.html",
    "server/areas/application/application_controller.js",
    "file"
  ],
  [
    "server/areas/application/application_controller.js~applicationcontroller#constructor",
    "class/server/areas/application/application_controller.js~ApplicationController.html#instance-constructor-constructor",
    "server/areas/application/application_controller.js~ApplicationController#constructor",
    "method"
  ],
  [
    "server/areas/application/application_controller.js~applicationcontroller#create",
    "class/server/areas/application/application_controller.js~ApplicationController.html#instance-method-create",
    "server/areas/application/application_controller.js~ApplicationController#create",
    "method"
  ],
  [
    "server/areas/application/application_controller.js~applicationcontroller#routes",
    "class/server/areas/application/application_controller.js~ApplicationController.html#instance-method-routes",
    "server/areas/application/application_controller.js~ApplicationController#routes",
    "method"
  ],
  [
    "server/areas/base_controller.js",
    "file/server/areas/base_controller.js.html",
    "server/areas/base_controller.js",
    "file"
  ],
  [
    "server/areas/base_controller.js~basecontroller#constructor",
    "class/server/areas/base_controller.js~BaseController.html#instance-constructor-constructor",
    "server/areas/base_controller.js~BaseController#constructor",
    "method"
  ],
  [
    "server/areas/base_controller.js~basecontroller#routes",
    "class/server/areas/base_controller.js~BaseController.html#instance-method-routes",
    "server/areas/base_controller.js~BaseController#routes",
    "method"
  ],
  [
    "server/areas/base_controller.js~hapireply",
    "external/index.html",
    "server/areas/base_controller.js~HapiReply",
    "external"
  ],
  [
    "server/areas/connector/connector_controller.js",
    "file/server/areas/connector/connector_controller.js.html",
    "server/areas/connector/connector_controller.js",
    "file"
  ],
  [
    "server/areas/connector/connector_controller.js~connectorcontroller#connect",
    "class/server/areas/connector/connector_controller.js~ConnectorController.html#instance-method-connect",
    "server/areas/connector/connector_controller.js~ConnectorController#connect",
    "method"
  ],
  [
    "server/areas/connector/connector_controller.js~connectorcontroller#connectorbundle",
    "class/server/areas/connector/connector_controller.js~ConnectorController.html#instance-method-connectorBundle",
    "server/areas/connector/connector_controller.js~ConnectorController#connectorBundle",
    "method"
  ],
  [
    "server/areas/connector/connector_controller.js~connectorcontroller#constructor",
    "class/server/areas/connector/connector_controller.js~ConnectorController.html#instance-constructor-constructor",
    "server/areas/connector/connector_controller.js~ConnectorController#constructor",
    "method"
  ],
  [
    "server/areas/connector/connector_controller.js~connectorcontroller#list",
    "class/server/areas/connector/connector_controller.js~ConnectorController.html#instance-method-list",
    "server/areas/connector/connector_controller.js~ConnectorController#list",
    "method"
  ],
  [
    "server/areas/connector/connector_controller.js~connectorcontroller#routes",
    "class/server/areas/connector/connector_controller.js~ConnectorController.html#instance-method-routes",
    "server/areas/connector/connector_controller.js~ConnectorController#routes",
    "method"
  ],
  [
    "server/areas/console/console_controller.js",
    "file/server/areas/console/console_controller.js.html",
    "server/areas/console/console_controller.js",
    "file"
  ],
  [
    "server/areas/console/console_controller.js~consolecontroller#constructor",
    "class/server/areas/console/console_controller.js~ConsoleController.html#instance-constructor-constructor",
    "server/areas/console/console_controller.js~ConsoleController#constructor",
    "method"
  ],
  [
    "server/areas/console/console_controller.js~consolecontroller#get",
    "class/server/areas/console/console_controller.js~ConsoleController.html#instance-method-get",
    "server/areas/console/console_controller.js~ConsoleController#get",
    "method"
  ],
  [
    "server/areas/console/console_controller.js~consolecontroller#routes",
    "class/server/areas/console/console_controller.js~ConsoleController.html#instance-method-routes",
    "server/areas/console/console_controller.js~ConsoleController#routes",
    "method"
  ],
  [
    "server/areas/editor/editor_controller.js",
    "file/server/areas/editor/editor_controller.js.html",
    "server/areas/editor/editor_controller.js",
    "file"
  ],
  [
    "server/areas/editor/editor_controller.js~editorcontroller#constructor",
    "class/server/areas/editor/editor_controller.js~EditorController.html#instance-constructor-constructor",
    "server/areas/editor/editor_controller.js~EditorController#constructor",
    "method"
  ],
  [
    "server/areas/editor/editor_controller.js~editorcontroller#routes",
    "class/server/areas/editor/editor_controller.js~EditorController.html#instance-method-routes",
    "server/areas/editor/editor_controller.js~EditorController#routes",
    "method"
  ],
  [
    "server/areas/editor/editor_controller.js~editorcontroller#savescript",
    "class/server/areas/editor/editor_controller.js~EditorController.html#instance-method-saveScript",
    "server/areas/editor/editor_controller.js~EditorController#saveScript",
    "method"
  ],
  [
    "server/areas/editor/editor_controller.js~editorcontroller#script",
    "class/server/areas/editor/editor_controller.js~EditorController.html#instance-method-script",
    "server/areas/editor/editor_controller.js~EditorController#script",
    "method"
  ],
  [
    "server/areas/editor/editor_controller.js~editorcontroller#state",
    "class/server/areas/editor/editor_controller.js~EditorController.html#instance-method-state",
    "server/areas/editor/editor_controller.js~EditorController#state",
    "method"
  ],
  [
    "server/areas/event/event_controller.js",
    "file/server/areas/event/event_controller.js.html",
    "server/areas/event/event_controller.js",
    "file"
  ],
  [
    "server/areas/event/event_controller.js~eventcontroller#constructor",
    "class/server/areas/event/event_controller.js~EventController.html#instance-constructor-constructor",
    "server/areas/event/event_controller.js~EventController#constructor",
    "method"
  ],
  [
    "server/areas/event/event_controller.js~eventcontroller#create",
    "class/server/areas/event/event_controller.js~EventController.html#instance-method-create",
    "server/areas/event/event_controller.js~EventController#create",
    "method"
  ],
  [
    "server/areas/event/event_controller.js~eventcontroller#routes",
    "class/server/areas/event/event_controller.js~EventController.html#instance-method-routes",
    "server/areas/event/event_controller.js~EventController#routes",
    "method"
  ],
  [
    "server/areas/healthcheck/healthcheck_controller.js",
    "file/server/areas/healthcheck/healthcheck_controller.js.html",
    "server/areas/healthcheck/healthcheck_controller.js",
    "file"
  ],
  [
    "server/areas/healthcheck/healthcheck_controller.js~healthcheckcontroller#constructor",
    "class/server/areas/healthcheck/healthcheck_controller.js~HealthcheckController.html#instance-constructor-constructor",
    "server/areas/healthcheck/healthcheck_controller.js~HealthcheckController#constructor",
    "method"
  ],
  [
    "server/areas/healthcheck/healthcheck_controller.js~healthcheckcontroller#healthcheck",
    "class/server/areas/healthcheck/healthcheck_controller.js~HealthcheckController.html#instance-method-healthcheck",
    "server/areas/healthcheck/healthcheck_controller.js~HealthcheckController#healthcheck",
    "method"
  ],
  [
    "server/areas/healthcheck/healthcheck_controller.js~healthcheckcontroller#routes",
    "class/server/areas/healthcheck/healthcheck_controller.js~HealthcheckController.html#instance-method-routes",
    "server/areas/healthcheck/healthcheck_controller.js~HealthcheckController#routes",
    "method"
  ],
  [
    "server/areas/organisation/organisation_controller.js",
    "file/server/areas/organisation/organisation_controller.js.html",
    "server/areas/organisation/organisation_controller.js",
    "file"
  ],
  [
    "server/areas/organisation/organisation_controller.js~organisationcontroller#constructor",
    "class/server/areas/organisation/organisation_controller.js~OrganisationController.html#instance-constructor-constructor",
    "server/areas/organisation/organisation_controller.js~OrganisationController#constructor",
    "method"
  ],
  [
    "server/areas/organisation/organisation_controller.js~organisationcontroller#create",
    "class/server/areas/organisation/organisation_controller.js~OrganisationController.html#instance-method-create",
    "server/areas/organisation/organisation_controller.js~OrganisationController#create",
    "method"
  ],
  [
    "server/areas/organisation/organisation_controller.js~organisationcontroller#fetch",
    "class/server/areas/organisation/organisation_controller.js~OrganisationController.html#instance-method-fetch",
    "server/areas/organisation/organisation_controller.js~OrganisationController#fetch",
    "method"
  ],
  [
    "server/areas/organisation/organisation_controller.js~organisationcontroller#routes",
    "class/server/areas/organisation/organisation_controller.js~OrganisationController.html#instance-method-routes",
    "server/areas/organisation/organisation_controller.js~OrganisationController#routes",
    "method"
  ],
  [
    "server/areas/session/session_controller.js",
    "file/server/areas/session/session_controller.js.html",
    "server/areas/session/session_controller.js",
    "file"
  ],
  [
    "server/areas/session/session_controller.js~sessioncontroller#constructor",
    "class/server/areas/session/session_controller.js~SessionController.html#instance-constructor-constructor",
    "server/areas/session/session_controller.js~SessionController#constructor",
    "method"
  ],
  [
    "server/areas/session/session_controller.js~sessioncontroller#create",
    "class/server/areas/session/session_controller.js~SessionController.html#instance-method-create",
    "server/areas/session/session_controller.js~SessionController#create",
    "method"
  ],
  [
    "server/areas/session/session_controller.js~sessioncontroller#current",
    "class/server/areas/session/session_controller.js~SessionController.html#instance-method-current",
    "server/areas/session/session_controller.js~SessionController#current",
    "method"
  ],
  [
    "server/areas/session/session_controller.js~sessioncontroller#destroy",
    "class/server/areas/session/session_controller.js~SessionController.html#instance-method-destroy",
    "server/areas/session/session_controller.js~SessionController#destroy",
    "method"
  ],
  [
    "server/areas/session/session_controller.js~sessioncontroller#routes",
    "class/server/areas/session/session_controller.js~SessionController.html#instance-method-routes",
    "server/areas/session/session_controller.js~SessionController#routes",
    "method"
  ],
  [
    "server/areas/session/session_controller.js~sessioncontroller#updateapplication",
    "class/server/areas/session/session_controller.js~SessionController.html#instance-method-updateApplication",
    "server/areas/session/session_controller.js~SessionController#updateApplication",
    "method"
  ],
  [
    "server/areas/session/session_controller.js~sessioncontroller#updateorganisation",
    "class/server/areas/session/session_controller.js~SessionController.html#instance-method-updateOrganisation",
    "server/areas/session/session_controller.js~SessionController#updateOrganisation",
    "method"
  ],
  [
    "server/areas/user/user_controller.js",
    "file/server/areas/user/user_controller.js.html",
    "server/areas/user/user_controller.js",
    "file"
  ],
  [
    "server/areas/user/user_controller.js~usercontroller#activateforgottenpassword",
    "class/server/areas/user/user_controller.js~UserController.html#instance-method-activateForgottenPassword",
    "server/areas/user/user_controller.js~UserController#activateForgottenPassword",
    "method"
  ],
  [
    "server/areas/user/user_controller.js~usercontroller#constructor",
    "class/server/areas/user/user_controller.js~UserController.html#instance-constructor-constructor",
    "server/areas/user/user_controller.js~UserController#constructor",
    "method"
  ],
  [
    "server/areas/user/user_controller.js~usercontroller#create",
    "class/server/areas/user/user_controller.js~UserController.html#instance-method-create",
    "server/areas/user/user_controller.js~UserController#create",
    "method"
  ],
  [
    "server/areas/user/user_controller.js~usercontroller#generateforgottenpassword",
    "class/server/areas/user/user_controller.js~UserController.html#instance-method-generateForgottenPassword",
    "server/areas/user/user_controller.js~UserController#generateForgottenPassword",
    "method"
  ],
  [
    "server/areas/user/user_controller.js~usercontroller#routes",
    "class/server/areas/user/user_controller.js~UserController.html#instance-method-routes",
    "server/areas/user/user_controller.js~UserController#routes",
    "method"
  ],
  [
    "server/configuration/authentication.js",
    "file/server/configuration/authentication.js.html",
    "server/configuration/authentication.js",
    "file"
  ],
  [
    "server/configuration/authentication.js~authenticationconfigurator#configure",
    "class/server/configuration/authentication.js~AuthenticationConfigurator.html#instance-method-configure",
    "server/configuration/authentication.js~AuthenticationConfigurator#configure",
    "method"
  ],
  [
    "server/configuration/base_configurator.js",
    "file/server/configuration/base_configurator.js.html",
    "server/configuration/base_configurator.js",
    "file"
  ],
  [
    "server/configuration/base_configurator.js~baseconfigurator#configure",
    "class/server/configuration/base_configurator.js~BaseConfigurator.html#instance-method-configure",
    "server/configuration/base_configurator.js~BaseConfigurator#configure",
    "method"
  ],
  [
    "server/configuration/base_configurator.js~baseconfigurator#constructor",
    "class/server/configuration/base_configurator.js~BaseConfigurator.html#instance-constructor-constructor",
    "server/configuration/base_configurator.js~BaseConfigurator#constructor",
    "method"
  ],
  [
    "server/configuration/index.js",
    "file/server/configuration/index.js.html",
    "server/configuration/index.js",
    "file"
  ],
  [
    "server/configuration/logging.js",
    "file/server/configuration/logging.js.html",
    "server/configuration/logging.js",
    "file"
  ],
  [
    "server/configuration/logging.js~loggingconfigurator#configure",
    "class/server/configuration/logging.js~LoggingConfigurator.html#instance-method-configure",
    "server/configuration/logging.js~LoggingConfigurator#configure",
    "method"
  ],
  [
    "server/configuration/routes.js",
    "file/server/configuration/routes.js.html",
    "server/configuration/routes.js",
    "file"
  ],
  [
    "server/configuration/routes.js~routeconfigurator#configure",
    "class/server/configuration/routes.js~RouteConfigurator.html#instance-method-configure",
    "server/configuration/routes.js~RouteConfigurator#configure",
    "method"
  ],
  [
    "server/configuration/routes.js~routeconfigurator#constructor",
    "class/server/configuration/routes.js~RouteConfigurator.html#instance-constructor-constructor",
    "server/configuration/routes.js~RouteConfigurator#constructor",
    "method"
  ],
  [
    "server/configuration/routes.js~routeconfigurator#mapcontrollerroutes",
    "class/server/configuration/routes.js~RouteConfigurator.html#instance-method-mapControllerRoutes",
    "server/configuration/routes.js~RouteConfigurator#mapControllerRoutes",
    "method"
  ],
  [
    "server/configuration/routes.js~routeconfigurator#mapdefaultroute",
    "class/server/configuration/routes.js~RouteConfigurator.html#instance-method-mapDefaultRoute",
    "server/configuration/routes.js~RouteConfigurator#mapDefaultRoute",
    "method"
  ],
  [
    "server/configuration/routes.js~routeconfigurator#mapstaticroutes",
    "class/server/configuration/routes.js~RouteConfigurator.html#instance-method-mapStaticRoutes",
    "server/configuration/routes.js~RouteConfigurator#mapStaticRoutes",
    "method"
  ],
  [
    "server/configuration/server.js",
    "file/server/configuration/server.js.html",
    "server/configuration/server.js",
    "file"
  ],
  [
    "server/configuration/server.js~serverconfigurator#configure",
    "class/server/configuration/server.js~ServerConfigurator.html#instance-method-configure",
    "server/configuration/server.js~ServerConfigurator#configure",
    "method"
  ],
  [
    "server/configuration/server.js~serverconfigurator#constructor",
    "class/server/configuration/server.js~ServerConfigurator.html#instance-constructor-constructor",
    "server/configuration/server.js~ServerConfigurator#constructor",
    "method"
  ],
  [
    "server/index.js",
    "file/server/index.js.html",
    "server/index.js",
    "file"
  ],
  [
    "server/index.js~portalserver#constructor",
    "class/server/index.js~PortalServer.html#instance-constructor-constructor",
    "server/index.js~PortalServer#constructor",
    "method"
  ],
  [
    "server/index.js~portalserver#start",
    "class/server/index.js~PortalServer.html#instance-method-start",
    "server/index.js~PortalServer#start",
    "method"
  ],
  [
    "server/logic/application.js",
    "file/server/logic/application.js.html",
    "server/logic/application.js",
    "file"
  ],
  [
    "server/logic/connector.js",
    "file/server/logic/connector.js.html",
    "server/logic/connector.js",
    "file"
  ],
  [
    "server/logic/console.js",
    "file/server/logic/console.js.html",
    "server/logic/console.js",
    "file"
  ],
  [
    "server/logic/editor.js",
    "file/server/logic/editor.js.html",
    "server/logic/editor.js",
    "file"
  ],
  [
    "server/logic/emails.js",
    "file/server/logic/emails.js.html",
    "server/logic/emails.js",
    "file"
  ],
  [
    "server/logic/event.js",
    "file/server/logic/event.js.html",
    "server/logic/event.js",
    "file"
  ],
  [
    "server/logic/index.js",
    "file/server/logic/index.js.html",
    "server/logic/index.js",
    "file"
  ],
  [
    "server/logic/organisation.js",
    "file/server/logic/organisation.js.html",
    "server/logic/organisation.js",
    "file"
  ],
  [
    "server/logic/session.js",
    "file/server/logic/session.js.html",
    "server/logic/session.js",
    "file"
  ],
  [
    "server/logic/settings.js",
    "file/server/logic/settings.js.html",
    "server/logic/settings.js",
    "file"
  ],
  [
    "server/logic/user.js",
    "file/server/logic/user.js.html",
    "server/logic/user.js",
    "file"
  ],
  [
    "server/models/connector_view_model.js",
    "file/server/models/connector_view_model.js.html",
    "server/models/connector_view_model.js",
    "file"
  ],
  [
    "server/models/connector_view_model.js~connectorviewmodel#codeforevent",
    "class/server/models/connector_view_model.js~ConnectorViewModel.html#instance-method-codeForEvent",
    "server/models/connector_view_model.js~ConnectorViewModel#codeForEvent",
    "method"
  ],
  [
    "server/models/connector_view_model.js~connectorviewmodel#constructor",
    "class/server/models/connector_view_model.js~ConnectorViewModel.html#instance-constructor-constructor",
    "server/models/connector_view_model.js~ConnectorViewModel#constructor",
    "method"
  ],
  [
    "server/models/connector_view_model.js~connectorviewmodel#events",
    "class/server/models/connector_view_model.js~ConnectorViewModel.html#instance-get-events",
    "server/models/connector_view_model.js~ConnectorViewModel#events",
    "member"
  ],
  [
    "server/models/connector_view_model.js~connectorviewmodel#key",
    "class/server/models/connector_view_model.js~ConnectorViewModel.html#instance-get-key",
    "server/models/connector_view_model.js~ConnectorViewModel#key",
    "member"
  ],
  [
    "server/models/connector_view_model.js~connectorviewmodel#name",
    "class/server/models/connector_view_model.js~ConnectorViewModel.html#instance-get-name",
    "server/models/connector_view_model.js~ConnectorViewModel#name",
    "member"
  ],
  [
    "server/models/connector_view_model.js~connectorviewmodel#populate",
    "class/server/models/connector_view_model.js~ConnectorViewModel.html#instance-method-populate",
    "server/models/connector_view_model.js~ConnectorViewModel#populate",
    "method"
  ],
  [
    "server/models/connector_view_model.js~connectorviewmodel#settings",
    "class/server/models/connector_view_model.js~ConnectorViewModel.html#instance-get-settings",
    "server/models/connector_view_model.js~ConnectorViewModel#settings",
    "member"
  ],
  [
    "server/models/connector_view_model.js~connectorviewmodel#tojson",
    "class/server/models/connector_view_model.js~ConnectorViewModel.html#instance-method-toJSON",
    "server/models/connector_view_model.js~ConnectorViewModel#toJSON",
    "method"
  ],
  [
    "server/models/connector_view_model.js~connectorviewmodel#type",
    "class/server/models/connector_view_model.js~ConnectorViewModel.html#instance-get-type",
    "server/models/connector_view_model.js~ConnectorViewModel#type",
    "member"
  ],
  [
    "server/utils/index.js",
    "file/server/utils/index.js.html",
    "server/utils/index.js",
    "file"
  ],
  [
    "server/utils/rabbit.js",
    "file/server/utils/rabbit.js.html",
    "server/utils/rabbit.js",
    "file"
  ],
  [
    "server/utils/string_utils.js",
    "file/server/utils/string_utils.js.html",
    "server/utils/string_utils.js",
    "file"
  ],
  [
    "tests/server/unit_tests/controllers/connector_controller_tests.js",
    "test-file/tests/server/unit_tests/controllers/connector_controller_tests.js.html",
    "tests/server/unit_tests/controllers/connector_controller_tests.js",
    "testFile"
  ],
  [
    "tests/server/unit_tests/controllers/editor_controller_tests.js",
    "test-file/tests/server/unit_tests/controllers/editor_controller_tests.js.html",
    "tests/server/unit_tests/controllers/editor_controller_tests.js",
    "testFile"
  ],
  [
    "tests/server/unit_tests/controllers/session_controller_tests.js",
    "test-file/tests/server/unit_tests/controllers/session_controller_tests.js.html",
    "tests/server/unit_tests/controllers/session_controller_tests.js",
    "testFile"
  ],
  [
    "tests/server/unit_tests/logic/application_tests.js",
    "test-file/tests/server/unit_tests/logic/application_tests.js.html",
    "tests/server/unit_tests/logic/application_tests.js",
    "testFile"
  ],
  [
    "tests/server/unit_tests/logic/connector_logic_tests.js",
    "test-file/tests/server/unit_tests/logic/connector_logic_tests.js.html",
    "tests/server/unit_tests/logic/connector_logic_tests.js",
    "testFile"
  ],
  [
    "tests/server/unit_tests/logic/editor_tests.js",
    "test-file/tests/server/unit_tests/logic/editor_tests.js.html",
    "tests/server/unit_tests/logic/editor_tests.js",
    "testFile"
  ],
  [
    "tests/server/unit_tests/logic/email_logic_tests.js",
    "test-file/tests/server/unit_tests/logic/email_logic_tests.js.html",
    "tests/server/unit_tests/logic/email_logic_tests.js",
    "testFile"
  ],
  [
    "tests/server/unit_tests/logic/event_tests.js",
    "test-file/tests/server/unit_tests/logic/event_tests.js.html",
    "tests/server/unit_tests/logic/event_tests.js",
    "testFile"
  ],
  [
    "tests/server/unit_tests/logic/organisation_tests.js",
    "test-file/tests/server/unit_tests/logic/organisation_tests.js.html",
    "tests/server/unit_tests/logic/organisation_tests.js",
    "testFile"
  ],
  [
    "tests/server/unit_tests/logic/session_tests.js",
    "test-file/tests/server/unit_tests/logic/session_tests.js.html",
    "tests/server/unit_tests/logic/session_tests.js",
    "testFile"
  ],
  [
    "tests/server/unit_tests/logic/user_logic_tests.js",
    "test-file/tests/server/unit_tests/logic/user_logic_tests.js.html",
    "tests/server/unit_tests/logic/user_logic_tests.js",
    "testFile"
  ],
  [
    "tests/server/unit_tests/server_tests.js",
    "test-file/tests/server/unit_tests/server_tests.js.html",
    "tests/server/unit_tests/server_tests.js",
    "testFile"
  ]
]