export const actions = {
  fleet: {
    STATUS_UPDATE: {
      IN_PROGRESS: 'FLEET:STATUSUPDATE:INPROGRESS',
      SUCCEEDED: 'FLEET:STATUSUPDATE:SUCCESS',
      FAILED: 'FLEET:STATUSUPDATE:FAILED'
    }
  },
  consul: {
    STATUS_UPDATE: {
      IN_PROGRESS: 'CONSUL:STATUSUPDATE:INPROGRESS',
      SUCCEEDED: 'CONSUL:STATUSUPDATE:SUCCESS',
      FAILED: 'CONSUL:STATUSUPDATE:FAILED'
    }
  },
  rabbit: {
    STATUS_UPDATE: {
      IN_PROGRESS: 'RABBIT:STATUSUPDATE:INPROGRESS',
      SUCCEEDED: 'RABBIT:STATUSUPDATE:SUCCESS',
      FAILED: 'RABBIT:STATUSUPDATE:FAILED'
    },
    STATISTICS_UPDATE: {
      IN_PROGRESS: 'RABBIT:STATSUPDATE:INPROGRESS',
      SUCCEEDED: 'RABBIT:STATSUPDATE:SUCCESS',
      FAILED: 'RABBIT:STATSUPDATE:FAILED'
    }
  }
}
