export const actions = {
  action: {
    PENDING: "ACTION:PENDING",
    FAILED: "ACTION:FAILED",
    SUCCESS: "ACTION:SUCCESS"
  },
  session: {
    LOGGED_IN: 'SESSION:LOGGED_IN',
    LOGGED_OUT: 'SESSION:LOGGED_OUT',
    UPDATE_SESSION: 'SESSION:UPDATE_SESSION'
  },
  organisation: {
    CREATE_ORGANISATION: 'ORGANISATION:CREATE_ORGANISATION',
    SWITCH_ORGANISATION: 'ORGANISATION:SWITCH_ORGANISATION',
    SET_ORGANISATIONS: 'ORGANISATION:SET_ORGANISATIONS'
  },
  user: {
    SET_USER: 'USER:SET_USER',
    CREATED: 'USER:CREATED',
    FORGOT_PASSWORD_CREATED: 'USER:FORGOT_PASSWORD_CREATED'
  },
  application: {
    CREATE_APPLICATION: 'APPLICATION:CREATE_APPLICATION',
    SWITCH_APPLICATION: 'APPLICATION:SWITCH_APPLICATION',
    SET_APPLICATIONS: 'APPLICATION:SET_APPLICATIONS'
  },
  connectors: {
    LOADED_CONNECTORS: 'CONNECTORS:LOADED_CONNECTORS'
  },
  editor: {
    LOADED_EDITOR: 'EDITOR:LOADED_EDITOR',
    LOADED_SCRIPT: 'EDITOR:LOADED_SCRIPT',
    SAVED_SCRIPT: {
      REQUESTING: 'EDITOR:SAVED_SCRIPT:REQUESTING',
      SUCCESS: 'EDITOR:SAVED_SCRIPT:SUCCESS',
      FAILED: 'EDITOR:SAVED_SCRIPT:FAILED'
    }
  },
  console: {
    POLL: {
      REQUESTING: 'CONSOLE:POLL:REQUESTING',
      SUCCESS: 'CONSOLE:POLL:SUCCESS',
      FAILED: 'CONSOLE:POLL:FAILED'
    }
  },
  event: {
    CREATE: {
      REQUESTING: 'EVENT:CREATE:REQUESTING',
      SUCCESS: 'EVENT:CREATE:SUCCESS',
      FAILED: 'EVENT:CREATE:FAILED'
    }
  },
  connector: {
    CONNECT: {
      REQUESTING: 'CONNECTOR:CONNECT:REQUESTING',
      SUCCESS: 'CONNECTOR:CONNECT:SUCCESS',
      FAILED: 'CONNECTOR:CONNECT:FAILED'
    }
  }
}
